### ISSUE TITLE
only register part works for me. in login and home pages e-earners loading page stuck

### ISSUE THREAD

**Issue by Alimzade** [ndiecodes/MLM-Solution#1]
![Ekran Alıntısı](https://user-images.githubusercontent.com/53145081/66375527-47d56d80-e9b6-11e9-884a-0630566945c7.PNG)

**Comment by voidnerd** [comment]
Hey man, sorry I haven't been watching this repository.

Seeing your url (*/public/login*), The issue might be some of the assets are not being imported; hosting your laravel app that way breaks a lot of things.

You can manually set all paths so your app can find the assets or follow this tutorial to re-host your laravel app on shared hosting (https://dev.to/ndiecodes/deploying-laravel-on-shared-hosting-5chk )

**Comment by voidnerd** [comment]
I am closing this as your issue is not with the codebase but with your hosting.
